name: Notify the Gchat Group for PRs from main repo
on:
  pull_request:
    types: [opened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      if: github.repository == ‘1-Platform/op-components’
      - name: Google Chat Notification
        uses: gautamkrishnar/google-chat-notification@master
        with:
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
